---
- hosts: all
  remote_user: vagrant
  become: True
  become_method: sudo
  gather_facts: True
  roles:
    # - geerlingguy.jenkins
    # - geerlingguy.apache
    - geerlingguy.repo-remi
    - geerlingguy.php
    # - geerlingguy.mysql
    # - geerlingguy.docker
